- name: Install EPEL
  yum:
          name: epel-release
          state: present
- name: Install NGINX
  yum:
          name: nginx
          state: present
- name: Enable and start NGINX service
  systemd:
          name: nginx
          state: started
          enabled: true
- name: Configure NGINX
  template:
          src: templates/backend.conf
          dest: /etc/nginx/conf.d/{{ backend_name }}.conf
  notify: "restart nginx"
