- name: Apply Common
  hosts: all
  vars:
  tasks:
  - import_role:
      name: common
- name: Install Jenkins
  hosts: host04
  become: true
  tasks:
  - import_role:
      name: java
  - import_role:
      name: jenkins
- name: Install nginx
  hosts: host03
  become: true
  tasks:
  - include_role:
      name: nginx
    vars:
      backend_port: "{{item.port}}"
      backend_name: "{{item.name}}"
      backend_host: "{{item.host}}"
      listen: "{{item.listen}}"
    loop:
      - { name: 'host04', host: 'host04', listen: 7777, port: 8080 }
      - { name: 'host05', host: 'host05', listen: 8888, port: 8080 }
  
