- name: Install Jenkins
  hosts: host04
  become: true
  tasks:
  - import_role:
      name: jenkins
- name: Install Nexus
  hosts: host05
  become: true
  tasks:
  - import_role:
      name: common
  - import_role:
      name: java
  - import_role:
      name: nexus
