- name: install openjdk
  yum:
    name: java-1.8.0-openjdk
    state: present
  become: true
  when: ansible_distribution == "CentOS"
- name: install openjdk
  apt:
    name: openjdk-8-jdk
    state: present
  become: true
  when: ansible_distribution == "Ubuntu"
