- name: install openjdk
  yum:
    name: java-1.8.0-openjdk-devel
    state: present
  become: true
  when: ansible_distribution == "CentOS"
- name: install openjdk
  apt:
    name: openjdk-8-jre
    state: present
  become: true
  when: ansible_distribution == "Ubuntu"