- name: download jenkins repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
  become: true
- name: import jenkins key
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
  become: true
- name: install jenkins
  yum:
    name: jenkins
    state: present
  become: true
- name: start jenkins
  systemd:
    name: jenkins
    state: started
  become: true
- name: enable jenkins
  systemd:
    name: jenkins
    enabled: true
  become: true
- name: check jenkins is up
  shell: curl localhost:8080
  retries: 5
  delay: 10
  register: curl_result
  until: curl_result is succeeded
  become: true  
- name: init password jenkin
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  retries: 5
  delay: 10
  register: result
  until: result is succeeded
  become: true
- name: print init password jenkins
  debug:
    var: result.stdout