---
- name: install Jenkins Repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
- name: install jenkins repository key
  rpm_key:
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present
- name: install jenkins
  yum:
    name: jenkins
    state: present
- name: start and enable jenkins service
  service:
    name: jenkins
    state: started
    enabled: true
- name: ensure jenkins is started
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: initialAdminPassword
  retries: 5
  delay: 10
  until: initialAdminPassword is succeeded
- name: output initial admin password
  debug:
    var: initialAdminPassword.stdout
  when: initialAdminPassword is succeeded
