- name: install wget
  yum:
    name: wget
    state: present
  become: true
- name: disable selinux
  selinux: 
    state: disabled
  become: true
  register: task_result
  notify: "reboot"
- name: install tar
  yum:
    name: tar
    state: present
  become: true