- name: install wget
  yum:
    name: wget
    state: present
  become: true
- name: install tar
  yum:
    name: tar
    state: present
  become: true
- name: disable selinux
  selinux: 
    state: disabled
  become: true
  register: task_result
- name: reboot
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: task_result is changed
- name: wait_reboot
  wait_for_connection:
      connect_timeout: "20"
      sleep: "5"
      delay: "20"
      timeout: "300"
  when: task_result is changed