- name: install wget
  yum:
    name: wget
    state: present
  become: true
- name: install tar
  yum:
    name: tar
    state: present
  become: true
- name: disable selinux
  selinux: 
    state: disabled
  become: true
- name: restart vms
  command: echo "this task will restart the vms"
  notify: "reboot vm"